//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_movements
    {
        public int movement_id { get; set; }
        public System.DateTime movement_datetime { get; set; }
        public string movement_type { get; set; }
        public int product_id { get; set; }
        public decimal qty_signed { get; set; }
        public string reference_table { get; set; }
        public Nullable<int> reference_id { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        public virtual products products { get; set; }
    }
}
