//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Espiga_DBEntities : DbContext
    {
        public Espiga_DBEntities()
            : base("name=Espiga_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<product_categories> product_categories { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<promotions> promotions { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<taxes> taxes { get; set; }
        public virtual DbSet<user_addresses> user_addresses { get; set; }
        public virtual DbSet<user_phones> user_phones { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<cantons> cantons { get; set; }
        public virtual DbSet<districts> districts { get; set; }
        public virtual DbSet<provinces> provinces { get; set; }
        public virtual DbSet<inventory_movements> inventory_movements { get; set; }
        public virtual DbSet<inventory_stock> inventory_stock { get; set; }
        public virtual DbSet<payment_terms> payment_terms { get; set; }
        public virtual DbSet<purchase_invoice_lines> purchase_invoice_lines { get; set; }
        public virtual DbSet<purchase_invoices> purchase_invoices { get; set; }
        public virtual DbSet<supplier_payments> supplier_payments { get; set; }
        public virtual DbSet<suppliers> suppliers { get; set; }
        public virtual DbSet<sales_invoice_lines> sales_invoice_lines { get; set; }
        public virtual DbSet<sales_invoices> sales_invoices { get; set; }
        public virtual DbSet<shopping_cart> shopping_cart { get; set; }
        public virtual DbSet<purchase_order_details> purchase_order_details { get; set; }
        public virtual DbSet<purchase_orders> purchase_orders { get; set; }
        public virtual DbSet<sales_invoice_payments> sales_invoice_payments { get; set; }
    
        public virtual ObjectResult<GetUserById_Result> GetUserById(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserById_Result>("GetUserById", userIdParameter);
        }
    
        public virtual ObjectResult<LoginUser_Result> LoginUser(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginUser_Result>("LoginUser", emailParameter, passwordParameter);
        }
    
        public virtual int RegisterProduct(string sku, string productName, string description, string imageUrl, Nullable<int> categoryId, string unitOfMeasure, Nullable<decimal> minStock, Nullable<int> taxId, Nullable<decimal> unitPrice, string createdBy)
        {
            var skuParameter = sku != null ?
                new ObjectParameter("Sku", sku) :
                new ObjectParameter("Sku", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var imageUrlParameter = imageUrl != null ?
                new ObjectParameter("ImageUrl", imageUrl) :
                new ObjectParameter("ImageUrl", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var unitOfMeasureParameter = unitOfMeasure != null ?
                new ObjectParameter("UnitOfMeasure", unitOfMeasure) :
                new ObjectParameter("UnitOfMeasure", typeof(string));
    
            var minStockParameter = minStock.HasValue ?
                new ObjectParameter("MinStock", minStock) :
                new ObjectParameter("MinStock", typeof(decimal));
    
            var taxIdParameter = taxId.HasValue ?
                new ObjectParameter("TaxId", taxId) :
                new ObjectParameter("TaxId", typeof(int));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("UnitPrice", unitPrice) :
                new ObjectParameter("UnitPrice", typeof(decimal));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegisterProduct", skuParameter, productNameParameter, descriptionParameter, imageUrlParameter, categoryIdParameter, unitOfMeasureParameter, minStockParameter, taxIdParameter, unitPriceParameter, createdByParameter);
        }
    
        public virtual int RegisterUser(Nullable<int> roleId, string identification, string name, string email, string password, string createdBy)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var identificationParameter = identification != null ?
                new ObjectParameter("Identification", identification) :
                new ObjectParameter("Identification", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegisterUser", roleIdParameter, identificationParameter, nameParameter, emailParameter, passwordParameter, createdByParameter);
        }
    
        public virtual int UpdatePassword(string password, Nullable<int> user_id, string modifiedBy)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("User_id", user_id) :
                new ObjectParameter("User_id", typeof(int));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePassword", passwordParameter, user_idParameter, modifiedByParameter);
        }
    
        public virtual int UpdateUser(Nullable<int> userId, string identification, string name, string email, string modifiedBy)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var identificationParameter = identification != null ?
                new ObjectParameter("Identification", identification) :
                new ObjectParameter("Identification", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", userIdParameter, identificationParameter, nameParameter, emailParameter, modifiedByParameter);
        }
    
        public virtual ObjectResult<ValidateEmail_Result> ValidateEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidateEmail_Result>("ValidateEmail", emailParameter);
        }
    
        public virtual ObjectResult<AdministerPaymentTerms_Result> AdministerPaymentTerms(string accion, Nullable<int> termId, string termName, Nullable<int> daysDue, string createdBy, string modifiedBy, string actionValue, Nullable<System.DateTime> createdAt, Nullable<System.DateTime> modifiedAt)
        {
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            var termIdParameter = termId.HasValue ?
                new ObjectParameter("TermId", termId) :
                new ObjectParameter("TermId", typeof(int));
    
            var termNameParameter = termName != null ?
                new ObjectParameter("TermName", termName) :
                new ObjectParameter("TermName", typeof(string));
    
            var daysDueParameter = daysDue.HasValue ?
                new ObjectParameter("DaysDue", daysDue) :
                new ObjectParameter("DaysDue", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            var actionValueParameter = actionValue != null ?
                new ObjectParameter("ActionValue", actionValue) :
                new ObjectParameter("ActionValue", typeof(string));
    
            var createdAtParameter = createdAt.HasValue ?
                new ObjectParameter("CreatedAt", createdAt) :
                new ObjectParameter("CreatedAt", typeof(System.DateTime));
    
            var modifiedAtParameter = modifiedAt.HasValue ?
                new ObjectParameter("ModifiedAt", modifiedAt) :
                new ObjectParameter("ModifiedAt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdministerPaymentTerms_Result>("AdministerPaymentTerms", accionParameter, termIdParameter, termNameParameter, daysDueParameter, createdByParameter, modifiedByParameter, actionValueParameter, createdAtParameter, modifiedAtParameter);
        }
    
        public virtual int InsertProduct(string product_name, string sku, string description, string image_url, Nullable<int> category_id, string unit_of_measure, Nullable<decimal> min_stock, Nullable<int> tax_id, Nullable<bool> is_active, string user)
        {
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var skuParameter = sku != null ?
                new ObjectParameter("sku", sku) :
                new ObjectParameter("sku", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var image_urlParameter = image_url != null ?
                new ObjectParameter("image_url", image_url) :
                new ObjectParameter("image_url", typeof(string));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            var unit_of_measureParameter = unit_of_measure != null ?
                new ObjectParameter("unit_of_measure", unit_of_measure) :
                new ObjectParameter("unit_of_measure", typeof(string));
    
            var min_stockParameter = min_stock.HasValue ?
                new ObjectParameter("min_stock", min_stock) :
                new ObjectParameter("min_stock", typeof(decimal));
    
            var tax_idParameter = tax_id.HasValue ?
                new ObjectParameter("tax_id", tax_id) :
                new ObjectParameter("tax_id", typeof(int));
    
            var is_activeParameter = is_active.HasValue ?
                new ObjectParameter("is_active", is_active) :
                new ObjectParameter("is_active", typeof(bool));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertProduct", product_nameParameter, skuParameter, descriptionParameter, image_urlParameter, category_idParameter, unit_of_measureParameter, min_stockParameter, tax_idParameter, is_activeParameter, userParameter);
        }
    
        public virtual int ToggleProductStatus(Nullable<int> product_id, string user)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ToggleProductStatus", product_idParameter, userParameter);
        }
    
        public virtual int UpdateProduct(Nullable<int> product_id, string product_name, string sku, string description, string image_url, Nullable<int> category_id, string unit_of_measure, Nullable<decimal> min_stock, Nullable<int> tax_id, Nullable<bool> is_active, string user)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var skuParameter = sku != null ?
                new ObjectParameter("sku", sku) :
                new ObjectParameter("sku", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var image_urlParameter = image_url != null ?
                new ObjectParameter("image_url", image_url) :
                new ObjectParameter("image_url", typeof(string));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            var unit_of_measureParameter = unit_of_measure != null ?
                new ObjectParameter("unit_of_measure", unit_of_measure) :
                new ObjectParameter("unit_of_measure", typeof(string));
    
            var min_stockParameter = min_stock.HasValue ?
                new ObjectParameter("min_stock", min_stock) :
                new ObjectParameter("min_stock", typeof(decimal));
    
            var tax_idParameter = tax_id.HasValue ?
                new ObjectParameter("tax_id", tax_id) :
                new ObjectParameter("tax_id", typeof(int));
    
            var is_activeParameter = is_active.HasValue ?
                new ObjectParameter("is_active", is_active) :
                new ObjectParameter("is_active", typeof(bool));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProduct", product_idParameter, product_nameParameter, skuParameter, descriptionParameter, image_urlParameter, category_idParameter, unit_of_measureParameter, min_stockParameter, tax_idParameter, is_activeParameter, userParameter);
        }
    }
}
