//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.inventory_movements = new HashSet<inventory_movements>();
            this.inventory_stock = new HashSet<inventory_stock>();
            this.purchase_invoice_lines = new HashSet<purchase_invoice_lines>();
            this.sales_invoice_lines = new HashSet<sales_invoice_lines>();
        }
    
        public int product_id { get; set; }
        public string sku { get; set; }
        public string product_name { get; set; }
        public string description { get; set; }
        public string image_url { get; set; }
        public int category_id { get; set; }
        public string unit_of_measure { get; set; }
        public decimal min_stock { get; set; }
        public int tax_id { get; set; }
        public byte is_active { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public Nullable<decimal> unit_price { get; set; }
    
        public virtual product_categories product_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_movements> inventory_movements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_stock> inventory_stock { get; set; }
        public virtual taxes taxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_invoice_lines> purchase_invoice_lines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_invoice_lines> sales_invoice_lines { get; set; }
    }
}
