//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promotions()
        {
            this.sales_invoice_lines = new HashSet<sales_invoice_lines>();
        }
    
        public int promotion_id { get; set; }
        public string promotion_name { get; set; }
        public string promotion_type { get; set; }
        public decimal promotion_value { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public byte is_active { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_invoice_lines> sales_invoice_lines { get; set; }
    }
}
