//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_invoice_lines
    {
        public int purchase_invoice_line_id { get; set; }
        public int purchase_invoice_id { get; set; }
        public int product_id { get; set; }
        public decimal qty { get; set; }
        public decimal unit_cost { get; set; }
        public int tax_id { get; set; }
        public decimal tax_amount { get; set; }
        public decimal line_total { get; set; }
        public string lot_reference { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        public virtual products products { get; set; }
        public virtual taxes taxes { get; set; }
        public virtual purchase_invoices purchase_invoices { get; set; }
    }
}
