//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_invoices()
        {
            this.purchase_invoice_lines = new HashSet<purchase_invoice_lines>();
            this.supplier_payments = new HashSet<supplier_payments>();
        }
    
        public int purchase_invoice_id { get; set; }
        public int supplier_id { get; set; }
        public string invoice_number { get; set; }
        public System.DateTime invoice_date { get; set; }
        public int term_id { get; set; }
        public System.DateTime due_date { get; set; }
        public decimal subtotal { get; set; }
        public decimal tax_total { get; set; }
        public decimal total { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        public virtual payment_terms payment_terms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_invoice_lines> purchase_invoice_lines { get; set; }
        public virtual suppliers suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_payments> supplier_payments { get; set; }
    }
}
