//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_invoices()
        {
            this.sales_invoice_lines = new HashSet<sales_invoice_lines>();
            this.sales_invoice_payments = new HashSet<sales_invoice_payments>();
        }
    
        public int sales_invoice_id { get; set; }
        public string sales_number { get; set; }
        public System.DateTime sales_datetime { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public string payment_method { get; set; }
        public string payment_reference { get; set; }
        public decimal subtotal { get; set; }
        public decimal discount_total { get; set; }
        public decimal tax_total { get; set; }
        public decimal total { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_invoice_lines> sales_invoice_lines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_invoice_payments> sales_invoice_payments { get; set; }
    }
}
