//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_invoice_lines
    {
        public int sales_invoice_line_id { get; set; }
        public int sales_invoice_id { get; set; }
        public int product_id { get; set; }
        public decimal qty_sold { get; set; }
        public decimal unit_price_list { get; set; }
        public decimal unit_price_final { get; set; }
        public Nullable<int> promotion_id { get; set; }
        public decimal discount_amount { get; set; }
        public int tax_id { get; set; }
        public decimal tax_amount { get; set; }
        public decimal line_subtotal { get; set; }
        public decimal line_total { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        public virtual products products { get; set; }
        public virtual promotions promotions { get; set; }
        public virtual taxes taxes { get; set; }
        public virtual sales_invoices sales_invoices { get; set; }
    }
}
