//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_PROYECTO_ESPIGADORADA.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_invoice_payments
    {
        public int sales_invoice_payment_id { get; set; }
        public int sales_invoice_id { get; set; }
        public string payment_method { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
    
        public virtual sales_invoices sales_invoices { get; set; }
    }
}
